language: csharp

dotnet: 3.1

script:
  - dotnet build HW1.sln -c Release
  - dotnet test -c Release --no-build CalculatorTests/CalculatorTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - dotnet test -c Release --no-build FSCalcTest/FSCalcTest.fsproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude"[Program*, Print, a@40]"

after_script:
  - bash <(curl -s https://codecov.io/bash)