language: csharp

dotnet: 3.1

script:
  - dotnet build HW1.sln -c Release
  - dotnet test -c Release --no-build CalculatorTests/CalculatorTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)
