language: csharp
solution: HW1.sln
install:
  - nuget restore HW1.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release HW1.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./CalculatorTests/bin/Debug/netcoreapp3.1/CalculatorTests.dll